const dummyData = {
  posts: [
    {
      id: 1,
      username: 'john_doe',
      fullName: 'John Doe',
      profileImage: 'https://picsum.photos/50',
      postImage: 'https://picsum.photos/500/500',
      comments: 120,
      description: 'Beautiful sunset at the beach!',
    },
    {
      id: 2,
      username: 'alex_kim',
      fullName: 'Alex Kim',
      profileImage: 'https://picsum.photos/50?random=2',
      postImage: 'https://picsum.photos/500/500?random=2',
      comments: 85,
      description: 'Mountain adventure!',
      bio: 'I love the mountains!',
    },
    {
      id: 3,
      username: 'meminkahraman',
      fullName: 'Muhammed Emin Kahraman',
      profileImage:
        'https://i0.wp.com/dogabilim.org/wp-content/uploads/2022/11/46842880695_a2fbd03c0c_k.jpg?fit=2047%2C1365&ssl=1',
      postImage:
        'https://cdn.ntvspor.net/807e92d628324f4fb3d6240f8891619c.jpg?mode=crop&w=940&h=626',
      comments: 1903,
      description: 'Rafa Sılva',
      bio: 'Hangimiz sevmedik çılgınlar gibi!',
    },
  ],
  reels: [
    {
      id: 1,
      username: 'john_doe',
      fullName: 'John Doe',
      profileImage: 'https://picsum.photos/50',
      video: 'https://www.w3schools.com/html/mov_bbb.mp4',
      comments: 120,
      description: 'Beautiful sunset at the beach!',
      post: 0,
      followers: 51,
      following: 100,
    },
    {
      id: 2,
      username: 'alex_kim',
      fullName: 'Alex Kim',
      profileImage: 'https://picsum.photos/50?random=2',
      video: 'https://www.w3schools.com/html/mov_bbb.mp4',
      comments: 85,
      description: 'Mountain adventure!',
    },
    {
      id: 3,
      username: 'meminkahraman',
      fullName: 'Muhammed Emin Kahraman',
      profileImage:
        'https://i0.wp.com/dogabilim.org/wp-content/uploads/2022/11/46842880695_a2fbd03c0c_k.jpg?fit=2047%2C1365&ssl=1',
      video: 'https://www.w3schools.com/html/mov_bbb.mp4',
      comments: 1903,
      description: 'Rafa Sılva',
    },
    {
      id: 4,
      username: 'fff',
      fullName: 'Johnfff Doe',
      profileImage: 'https://picsum.photos/50',
      video: 'https://www.w3schools.com/html/mov_bbb.mp4',
      comments: 120,
      description: 'Beautiful sunset at the beach!',
      post: 0,
      followers: 51,
      following: 100,
    },
  ],
  profile: [
    {
      id: 1,
      username: 'john_doe',
      fullName: 'John Doe',
      profileImage: 'https://picsum.photos/50',
      video: 'https://www.w3schools.com/html/mov_bbb.mp4',
      comments: 120,
      description: 'Beautiful sunset at the beach!',
      bio: 'I love the beach and sunset!',
      post: 0,
      followers: 51,
      following: 100,
    },
    {
      id: 2,
      username: 'alex_kim',
      fullName: 'Alex Kim',
      profileImage: 'https://picsum.photos/50?random=2',
      video: 'https://www.w3schools.com/html/mov_bbb.mp4',
      comments: 85,
      description: 'Mountain adventure!',
      bio: 'I love the mountains!',
      post: 1,
      followers: 100,
      following: 50,
    },
    {
      id: 3,
      username: 'meminkahraman',
      fullName: 'Muhammed Emin Kahraman',
      profileImage:
        'https://i0.wp.com/dogabilim.org/wp-content/uploads/2022/11/46842880695_a2fbd03c0c_k.jpg?fit=2047%2C1365&ssl=1',
      video: 'https://www.w3schools.com/html/mov_bbb.mp4',
      comments: 1903,
      description: 'Rafa Sılva',
      bio: 'Hangimiz sevmedik çılgınlar gibi!',
      post: 2,
      followers: 2000,
      following: 1500,
    },
  ],
};

export default dummyData;
